### ISSUE TITLE
incorrect double negation in template

### ISSUE THREAD

**Issue by femans** [oas-tools/oas-cli#11]
https://github.com/oas-tools/oas-cli/blob/7d9e6b201a58ad52f4529f1a2e90b219522e2839/templates/server/index.js.hbs#L61

the line should display the output if `disable !== true` in stead of `false`

**Comment by alesancor1** [comment]
That's true, I'm adding this issue to the project for the next patch, thanks :smile:

**Comment by alesancor1** [comment]
Fixed at #14
