### ISSUE TITLE
Pluralize "get all" (i.e. find many) endpoints in the generated OpenAPI document

### ISSUE THREAD

**Issue by ashryanbeats** [oas-tools/oas-cli#12]
# Context
Using the CLI to generate an OpenAPI document from an entity resource file for a given resource like `User`.

# Issue
The CLI generates the following lines containing an `operationId` that should probably be plural:

```
  /api/v1/users:
    get:
      description: Returns all users
      operationId: getUser
      responses:
        200:
          description: User list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
```

Note how the endpoint and description are plural as expected, and the success response is an array, yet the `operationId` is singular.

In turn, when generating a server based on this OpenAPI document, we'll end up with a controller that looks like this:

```
export function getUser(req, res) {
    service.getUser(req, res);
}
```

The function name would seem to imply that we'll only be getting one user back. However, the return value is going to be an array with any number of users.

# Expected outcome

Instead of `getUser`, the operation should be named `getUsers`. 

# The code
I haven't done a thorough check, but this appears to be where it's happening:
https://github.com/oas-tools/oas-cli/blob/bf53dd69f3f3bbc2c5cea9fa65df0c46bde021ad/templates/file/oas-doc.hbs#L13-L14

**Comment by alesancor1** [comment]
Fixed at #14
