### ISSUE TITLE
`204` should be an integer in the generated OpenAPI document 

### ISSUE THREAD

**Issue by ashryanbeats** [oas-tools/oas-cli#13]
When generating an OpenAPI document from an entity resource file, the 204 status is the only one that is generated as a string instead of as an integer.

Other (non-204) response statuses look like the following:

```
responses:
    200:
      description: Item found by id
```

For 204s, it will instead look like this:

```
responses:
    "204":
      description: Item deleted
```

## **To Reproduce**
1. Use an entity resource file to create an OpenAPI document with the CLI
2. In the interactive prompt, for any given entity, select the HTTP methods PUT and/or DELETE
3. Check the generated OpenAPI document to see that the 204s are noted as strings

## **Expected behavior**

Instead of `"204"`, the status should simply be `204` (no quotation marks).

**Comment by alesancor1** [comment]
Fixed at #14
