### ISSUE TITLE
[BUG] Array properties staring from an entity resource

### ISSUE THREAD

**Issue by borjar20** [oas-tools/oas-cli#5]
**Describe the bug**
When we declare arrays inside the entities and execute the cli for the creation of the oas-doc from a json. These are taken as their type in javascript `typeof [1,2,3,4] // Returns "object".`
**To Reproduce**
1. Create a json file like
```
[
    {
        "id": 1,
        "name": "User",
        "email": "user@example.com",
        "pets": [ 
           {
               "id": 1,
               "petName": "Garfield",
               "type": "Cat"
           }
        ]
    }
]
```
2. Exec `npx @oas-tools/cli init` to create OpenAPI File

**Comment by alesancor1** [comment]
This bug has been fixed in version `v1.0.2`. 

The updated CLI tool is already published an can be used through `npx @oas-tools/cli <command>`.
